services:
  - type: web
    name: Phoenix-MD
    env: node
    branch: main
    repo: https://github.com/AbhishekSuresh2/Phoenix-MD.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_NAME
        value: Phoenix-MD
      - key: OWNER_NAME
        value: Abhishek Suresh
      - key: OWNER_NUMBER
        value: 254741292931
      - key: PREFIX
        value: .
      - key: MODE
        value: private
      - key: STICKER_DATA
        value: ğŸ¯ğ™¿ğš‘ğš˜ğšğš—ğš’ğš¡-ğ™¼ğ™³;ğ™°ğš‹ğš‘ğš’ğšœğš‘ğšğš” ğš‚ğšğš›ğšğšœğš‘â˜˜ï¸
      - key: AUDIO_DATA
        value: Phoenix-MD;Abhishek Suresh;https://graph.org/file/8976892f2f615077b48cd.jpg
      - key: SUDO
        value: 254741292931
      - key: AUTO_STATUS_READ
        value: true
      - key: SPAM_COUNT
        value: 10
      - key: AUTO_REACT
        value: false
